services:
  laravel:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cbt
    restart: unless-stopped
    env_file:
      - .env.prod
    volumes:
      - cbt-storage:/app/storage
    networks:
      - caddy-net
      - mysql-db-v8-network

volumes:
  cbt-storage:

networks:
  mysql-db-v8-network:
    external: true
  caddy-net:
    external: true
